; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@3.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DTF_LITE_STATIC_MEMORY
    -std=gnu++17
lib_deps =
	adafruit/Adafruit MPU6050
	Madgwick
    madhephaestus/ESP32Servo
    https://github.com/spaziochirale/ArduTFLite